import type { Metadata } from 'next';
import './globals.css';
import ReactQueryProvider from '@/components/providers/ReactQueryProvider';
import { ReactQueryDevtools } from '@tanstack/react-query-devtools';
import { UserProvider } from '@/components/providers/UserProvider';
import { getUser } from '@/lib/auth';

import { gilroy } from '@/components/layout/fonts';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const userPromise = getUser();

    return (
        <html lang="en">
            <body className={`${gilroy.variable} antialiased`}>
                <ReactQueryProvider>
                    <UserProvider userPromise={userPromise}>
                        {children}
                        <ReactQueryDevtools />
                    </UserProvider>
                </ReactQueryProvider>
            </body>
        </html>
    );
}
